# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/TelaPrincipal.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ferramentaAlbir(object):
    def setupUi(self, ferramentaAlbir):
        ferramentaAlbir.setObjectName("ferramentaAlbir")
        ferramentaAlbir.resize(503, 418)
        self.centralwidget = QtWidgets.QWidget(ferramentaAlbir)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.listWidget_NomeArquivos = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget_NomeArquivos.setObjectName("listWidget_NomeArquivos")
        self.verticalLayout.addWidget(self.listWidget_NomeArquivos)
        self.pushButton_Selecionar = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Selecionar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_Selecionar.setWhatsThis("")
        self.pushButton_Selecionar.setObjectName("pushButton_Selecionar")
        self.verticalLayout.addWidget(self.pushButton_Selecionar)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_Limpar = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Limpar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_Limpar.setStyleSheet("background-color: rgb(196, 160, 0);")
        self.pushButton_Limpar.setObjectName("pushButton_Limpar")
        self.horizontalLayout.addWidget(self.pushButton_Limpar)
        self.pushButton_Enviar = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Enviar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_Enviar.setAutoFillBackground(False)
        self.pushButton_Enviar.setStyleSheet("background-color: rgb(78, 154, 6);")
        self.pushButton_Enviar.setObjectName("pushButton_Enviar")
        self.horizontalLayout.addWidget(self.pushButton_Enviar)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.gridLayout.addLayout(self.verticalLayout_2, 2, 0, 1, 1)
        self.label_PainelCentral = QtWidgets.QLabel(self.centralwidget)
        self.label_PainelCentral.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.label_PainelCentral.setFrameShape(QtWidgets.QFrame.Box)
        self.label_PainelCentral.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_PainelCentral.setMidLineWidth(0)
        self.label_PainelCentral.setAlignment(QtCore.Qt.AlignCenter)
        self.label_PainelCentral.setObjectName("label_PainelCentral")
        self.gridLayout.addWidget(self.label_PainelCentral, 0, 0, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 1, 0, 1, 1)
        ferramentaAlbir.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(ferramentaAlbir)
        self.statusbar.setObjectName("statusbar")
        ferramentaAlbir.setStatusBar(self.statusbar)

        self.retranslateUi(ferramentaAlbir)
        QtCore.QMetaObject.connectSlotsByName(ferramentaAlbir)

        self.pushButton_Selecionar.clicked.connect(self.listandoArquivos)
        self.pushButton_Limpar.clicked.connect(self.limpandoDiretorios)

    def listandoArquivos(self):
        self.listWidget_NomeArquivos.clear()
        # Buscando os arquivos... (Limitando apenas para imagens).
        Filename, _ = QtWidgets.QFileDialog.getOpenFileNames(
            None, "Selecione os arquivos", "", "Imagens (*.png *.xpm *.jpg)")
        if Filename:
            self.namesFiles = Filename
            self.listWidget_NomeArquivos.addItems(Filename)

    def limpandoDiretorios(self):
        # Verificar sempre se a variavel "namesFiles" eh ou nao NONE
        self.listWidget_NomeArquivos.clear()
        self.namesFiles = None


    def retranslateUi(self, ferramentaAlbir):
        _translate = QtCore.QCoreApplication.translate
        ferramentaAlbir.setWindowTitle(_translate("ferramentaAlbir", "Pagina Inicial"))
        self.pushButton_Selecionar.setText(_translate("ferramentaAlbir", "Selecionar arquivo"))
        self.pushButton_Limpar.setText(_translate("ferramentaAlbir", "Limpar"))
        self.pushButton_Enviar.setText(_translate("ferramentaAlbir", "Enviar"))
        self.label_PainelCentral.setText(_translate("ferramentaAlbir", "<html><head/><body><p><span style=\" font-size:22pt; font-weight:600;\">Ferramenta do Albir</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ferramentaAlbir = QtWidgets.QMainWindow()
    ui = Ui_ferramentaAlbir()
    ui.setupUi(ferramentaAlbir)
    ferramentaAlbir.show()
    sys.exit(app.exec_())
